vgg_16_weights: "weights.h5"
use_checkpoints: True
save_plots: True
model_checkpoints_path: "checkpoints/weights.h5"
features_file_urfd: "saved_features/features_urfd_tf.h5"
features_file_multicam: "saved_features/features_multicam_tf.h5"
features_file_fdd: "saved_features/features_fdd_tf.h5"
labels_file_urfd: "saved_features/labels_urfd_tf.h5"
labels_file_multicam: "saved_features/labels_multicam_tf.h5"
labels_file_fdd: "saved_features/labels_fdd_tf.h5"
plots_folder: "plots/"
num_features: 4096
batch_norm: True
learning_rate: 0.01
mini_batch_size: 2048
weight_0: 2
epochs: 1000
use_validation: True
use_validation_for_training: False
validation_size: 200
threshold: 0.5
sliding_window_length: 10
dataset: "UFRD"
camera_index: 0
output_path: "/home/denise/cs3244-fall-detection-project/output_dir/"
flow_path: "/home/denise/cs3244-fall-detection-project/flow_dir/"
mean_file: "flow_mean.mat"